# -*- coding: utf-8 -*-
"""rectangle_class.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17OU5YqvqNrIdyA5tjGAGn4rAtvO6BTfN
"""

!pip install Django

# ✅ Install Django if not already installed
!pip install -q Django

class Rectangle:
    def __init__(self, length: int, width: int):
        self.length = length
        self.width = width

    def __iter__(self):
        yield {'length': self.length}
        yield {'width': self.width}

# ✅ Test the class with example values
if __name__ == "__main__":
    rect = Rectangle(10, 5)

    for value in rect:
        print(value)